waypoints:
  recycle_bin:
    x: -0.179
    y: -3.728
    yaw: 1.75
    quaternion: [0.0, 0.0, 0.849, 0.529]

  alice_corner:
    x: 1.0
    y: 4.7
    yaw: -1.75
    quaternion: [0.0, 0.0, -0.855, 0.518]
